import { AlertTriangle, Loader2, Trash2 } from 'lucide-react';

export interface DeleteTarget { id: string; label: string; generated: number }

export function BatchDeleteDialog({ target, forceConfirm, deleting, onForceConfirm, onClose, onDelete }: { target: DeleteTarget; forceConfirm: boolean; deleting: boolean; onForceConfirm(value: boolean): void; onClose(): void; onDelete(): void }) {
  return <div className="absolute inset-0 z-[100] flex items-center justify-center bg-slate-900/60 backdrop-blur-sm"><div className="w-full max-w-md overflow-hidden rounded-[6px] bg-white shadow-lg">
    <div className="flex items-start gap-4 border-b border-rose-100 bg-rose-50 p-6"><div className="shrink-0 rounded-full bg-rose-100 p-3 text-rose-600"><Trash2 className="h-6 w-6" /></div><div><h3 className="mb-1 text-lg font-black text-slate-800">删除批次</h3><p className="text-sm font-medium leading-relaxed text-slate-600">即将删除批次 <span className="font-mono font-bold text-rose-600">{target.label}</span>,此操作不可恢复。</p></div></div>
    <div className="px-6 py-5">{target.generated > 0 ? <div className="space-y-4"><div className="flex items-start gap-3 rounded-[6px] border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" /><div>该批次已签发 <b>{target.generated}</b> 个溯源码。删除将连带清除全部关联溯源数据。</div></div><label className="flex cursor-pointer items-center gap-3"><input type="checkbox" checked={forceConfirm} onChange={event => onForceConfirm(event.target.checked)} className="h-4 w-4" /><span className="text-sm font-bold text-slate-700">我已知晓风险,确认强制删除该批次及全部关联溯源数据</span></label></div> : <p className="text-sm text-slate-500">该批次尚未签发溯源码,将连带删除其农事记录。</p>}</div>
    <div className="flex justify-end gap-3 border-t border-slate-100 p-5"><button onClick={onClose} disabled={deleting} className="px-5 py-2 text-sm font-bold text-slate-600">取消</button><button onClick={onDelete} disabled={deleting || (target.generated > 0 && !forceConfirm)} className="flex items-center gap-2 rounded-lg bg-rose-600 px-5 py-2 text-sm font-bold text-white disabled:opacity-50">{deleting && <Loader2 className="h-4 w-4 animate-spin" />}{deleting ? '删除中…' : target.generated > 0 ? '强制删除' : '确认删除'}</button></div>
  </div></div>;
}
